### ISSUE TITLE
CD for Orbit

### ISSUE THREAD

**Issue by guw** [eclipse/orbit#12]
Orbit should have a CD pipeline, i.e. after a PR is merged, a new repository should be provided and published under a "latest" or "main" (as in "main" branch) URL.

**Comment by jonahgraham** [comment]
Orbit does have a CD pipeline :-)

https://download.eclipse.org/tools/orbit/downloads/latest-I/ is populated within a couple of hours after a PR is merged using https://ci.eclipse.org/orbit/job/orbit-recipes/

**Comment by jonahgraham** [comment]
There are a number of other URLs as documented here https://download.eclipse.org/tools/orbit/downloads/

**Comment by guw** [comment]
That was quick. :) 

I was about to contribute a GH action.
```
name: Publish Repository to GitHub Pages

on:
  # manually from the Actions tab for now 
  # (should be automated for main branch at some point)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: Get Time for BUILD_ID
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: "YYYYMMDD_HHmm"

      - name: Get Branch name for BUILD_LABEL
        id: branch_name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven

      - name: Build
        env:
          BUILD_ID: "${{ steps.time.outputs.time }}"
          BUILD_TYPE: "N"
          BUILD_LABEL: "CI ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})" 
        run: |
          mvn clean install --batch-mode --update-snapshots
          mvn clean install --batch-mode --update-snapshots -f releng/aggregation-mirror-osgi/pom.xml
          mvn clean install --batch-mode --update-snapshots -f releng/aggregationfeature/pom.xml
          mvn clean install --batch-mode --update-snapshots -f releng/pom.xml

      - name: Deploy Update Site 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: <tbd>
          commit-message: "Publish p2 Repository ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})"
          single-commit: true
```
